application: tearoom6-jp
version: 1
runtime: php
api_version: 1

handlers:
- url: /script
  static_dir: script
- url: /style
  static_dir: style
- url: /img
  static_dir: img
- url: /html
  static_dir: html
- url: /.*
  static_files: html/index.html
  upload: html/index.html
